stepik_asp/Models/FavoriteViewModel.cs
namespace stepik_asp.Models
{
    public class FavoriteViewModel
    {
        public Guid Id { get; set; }
        public string UserId { get; set; }
        public List<ProductViewModel> Items { get; set; }
    }
}

stepik_asp/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using stepik.Db.Interfaces;
using stepik_asp.Helpers;
using stepik_asp.Interfaces;
using stepik_asp.Models;

namespace stepik_asp.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartsRepository _cartsRepository;
        private readonly IProductsRepository _productsRepository;

        public CartController(ICartsRepository cartsRepository, IProductsRepository productsRepository)
        {
            _cartsRepository = cartsRepository;
            _productsRepository = productsRepository;
        }
        private (string? userId, string? guestId) GetUserIdentifiers()
        {
            string? userId = User.Identity.IsAuthenticated ? User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value : null;

            string? guestId = Request.Cookies["GuestId"];

            if (userId == null && guestId == null)
            {
                guestId = Guid.NewGuid().ToString();
                Response.Cookies.Append("GuestId", guestId, new CookieOptions
                {
                    Expires = DateTimeOffset.UtcNow.AddHours(8)
                });
            }

            return (userId, guestId);
        }
        public IActionResult Index()
        {
            var (userId, guestId) = GetUserIdentifiers();
            var cart = _cartsRepository.TryGetByUserId(userId, guestId);
            return View(cart?.ToCartViewModel() ?? new CartViewModel());
        }

        public IActionResult Add(int productId)
        {
            var (userId, guestId) = GetUserIdentifiers();
            var product = _productsRepository.TryGetById(productId);

            _cartsRepository.Add(product, userId, guestId);
            return RedirectToAction("Index");
        }

        public IActionResult Clear()
        {
            var (userId, guestId) = GetUserIdentifiers();

            _cartsRepository.Clear(userId, guestId);
            return RedirectToAction("Index");
        }

        public IActionResult Decrease(int productId)
        {
            var (userId, guestId) = GetUserIdentifiers();

            _cartsRepository.Decrease(productId, userId, guestId);
            return RedirectToAction("Index");
        }
    }
}

stepik_asp/Controllers/FavoriteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using stepik.Db.Interfaces;
using stepik_asp.Helpers;
using stepik_asp.Models;

namespace stepik_asp.Controllers
{
    public class FavoriteController : Controller
    {
        private readonly IFavoritesRepository _favoritesRepository;
        private readonly IProductsRepository _productsRepository;

        public FavoriteController(IFavoritesRepository IfavoritesRepository, IProductsRepository productsRepository)
        {
            _favoritesRepository = IfavoritesRepository;
            _productsRepository = productsRepository;
        }

        private (string? userId, string? guestId) GetUserIdentifiers()
        {
            string? userId = User.Identity.IsAuthenticated ? User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value : null;
            string? guestId = Request.Cookies["GuestId"];
            if (userId == null && guestId == null)
            {
                guestId = Guid.NewGuid().ToString();
                Response.Cookies.Append("GuestId", guestId, new CookieOptions
                {
                    Expires = DateTimeOffset.UtcNow.AddHours(8)
                });
            }
            return (userId, guestId);
        }

        public IActionResult Index()
        {
            var(userId, guestId) = GetUserIdentifiers();
            var favorite = _favoritesRepository.TryGetByUserId(userId, guestId);

            return View(favorite.ToFavoriteViewModel());
        }
        public IActionResult Add(int productId)
        {
            var (userId, guestId) = GetUserIdentifiers();
            var product = _productsRepository.TryGetById(productId);
            if (product == null)
            {
                return RedirectToAction("Index","Home"); 
            }
            
            _favoritesRepository.Add(product, userId, guestId);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Delete(int productId)
        {
            var (userId, guestId) = GetUserIdentifiers();
            _favoritesRepository.Delete(productId, userId, guestId);
            return RedirectToAction("Index");
        }
        public IActionResult Clear()
        {
            var (userId, guestId) = GetUserIdentifiers();
            _favoritesRepository.Clear(userId, guestId);
            return RedirectToAction("Index");
        }
    }
}

stepik_asp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using stepik.Db.Interfaces;
using stepik_asp.Helpers;

namespace stepik_asp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductsRepository _productsRepository;

        public ProductController(IProductsRepository productsRepository)
        {
            _productsRepository = productsRepository;
        }
        public IActionResult Index(int id)
        {
            var product = _productsRepository.TryGetById(id);

            return View(product?.ToProductViewModel());
        }


    }
}

stepik_asp/Views/Favorite/Index.cshtml
@model FavoriteViewModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "Избранное";
}

<div class="text-center text-uppercase text-success mb-5 mt-5">
    <h2 class="row-title">Избранное</h2>
</div>

@if (Model != null && Model.Items?.Count > 0)
{
    <div class="row justify-content-center mt-3">
        @foreach (var product in Model.Items)
        {
            <div class="col-3 mb-3">
                <div class="card shadow">
                    <img class="card-img-top" src="@(string.IsNullOrEmpty(product.ImagePath)
           ? "/img/contact.png"
           : product.ImagePath)">
                    <div class="card-body text-center">
                        <a class="text-success"
                           asp-area=""
                           asp-controller="Product"
                           asp-action="Index"
                           asp-route-id="@product.Id">
                            <h5>@product.Name</h5>
                        </a>
                        <h2 class="text-danger">@product.Cost</h2>
                        <hr />
                        <h6>@product.Description</h6>
                        <hr />
                        <a class="btn btn-success"
                           asp-area=""
                           asp-controller="Cart"
                           asp-action="Add"
                           asp-route-productId="@product.Id">
                            Добавить в корзину
                        </a>
                        <a class="btn btn-outline-danger mt-3"
                           asp-area=""
                           asp-controller="Favorite"
                           asp-action="Delete"
                           asp-route-productId="@product.Id">
                            Убрать из избранного
                        </a>
                    </div>
                </div>
            </div>
        }

        <div class="text-center mt-5">
            <a class="btn btn-outline-danger"
               asp-area=""
               asp-controller="Favorite"
               asp-action="Clear">
                Очистить список избранного
            </a>
        </div>
    </div>
}
else
{
    <div class="text-center">
        <h2 class="row-title">В списке избранного нет товаров!</h2>
    </div>

}

<div class="text-center m-5">
    <a class="btn btn-outline-success"
       asp-area=""
       asp-controller="Home"
       asp-action="Index">
        Продолжить покупки
    </a>
</div>